// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADF1SJ459O1DKeECzE2-CzK4DfwOpDaQE',
    appId: '1:234951641678:web:8cf408b49f0a9bb489d11f',
    messagingSenderId: '234951641678',
    projectId: 'notes-fd32b',
    authDomain: 'notes-fd32b.firebaseapp.com',
    storageBucket: 'notes-fd32b.appspot.com',
    measurementId: 'G-BKNE22JKTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCLEKMlehK3v43_TfdGz7ovPWiF5cwIE',
    appId: '1:234951641678:android:b37034ba23a8706189d11f',
    messagingSenderId: '234951641678',
    projectId: 'notes-fd32b',
    storageBucket: 'notes-fd32b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOaeqQUpev0l6BbioyJAuXWj2RXvTxhfY',
    appId: '1:234951641678:ios:ff67c83ac0d8bdc789d11f',
    messagingSenderId: '234951641678',
    projectId: 'notes-fd32b',
    storageBucket: 'notes-fd32b.appspot.com',
    iosBundleId: 'com.example.notes',
  );
}
